In [2]:
import pandas as pd
from xgboost import XGBClassifier
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [8]:
data = pd.read_csv("./PhysionetChallenge2012-set-b.csv")

In [10]:
data.head()

,recordid,SAPS-I,SOFA,Length_of_stay,Survival,In-hospital_death,Age,Gender,Height,Weight,CCU,CSRU,SICU,DiasABP_first,GCS_first,Glucose_first,HR_first,MAP_first,NIDiasABP_first,NIMAP_first,NISysABP_first,RespRate_first,SaO2_first,Temp_first,DiasABP_last,GCS_last,Glucose_last,HR_last,MAP_last,NIDiasABP_last,NIMAP_last,NISysABP_last,RespRate_last,SaO2_last,Temp_last,DiasABP_lowest,GCS_lowest,Glucose_lowest,HR_lowest,MAP_lowest,NIDiasABP_lowest,NIMAP_lowest,NISysABP_lowest,RespRate_lowest,SaO2_lowest,Temp_lowest,DiasABP_highest,GCS_highest,Glucose_highest,HR_highest,MAP_highest,NIDiasABP_highest,NIMAP_highest,NISysABP_highest,RespRate_highest,SaO2_highest,Temp_highest,DiasABP_median,GCS_median,Glucose_median,HR_median,MAP_median,NIDiasABP_median,NIMAP_median,NISysABP_median,RespRate_median,SaO2_median,Temp_median,ALP_first,ALT_first,AST_first,Albumin_first,BUN_first,Bilirubin_first,Cholesterol_first,Creatinine_first,FiO2_first,HCO3_first,HCT_first,K_first,Lactate_first,Mg_first,Na_first,PaCO2_first,PaO2_first,Platelets_first,SysABP_first,TroponinI_first,TroponinT_first,WBC_first,Weight_first,pH_first,ALP_last,ALT_last,AST_last,Albumin_last,BUN_last,Bilirubin_last,Cholesterol_last,Creatinine_last,FiO2_last,HCO3_last,HCT_last,K_last,Lactate_last,Mg_last,Na_last,PaCO2_last,PaO2_last,Platelets_last,SysABP_last,TroponinI_last,TroponinT_last,WBC_last,Weight_last,pH_last,MechVentStartTime,MechVentDuration,MechVentLast8Hour,UrineOutputSum
0,142675,27,14,9,7,1,70.0,1.0,175.3,85.0,0,1,0,60.0,3.0,194.0,76.0,76.0,NaN,NaN,NaN,NaN,98.0,35.7,43.0,3.0,125.0,22.0,61.0,NaN,NaN,NaN,NaN,98.0,37.6,40.0,3.0,125.0,10.0,41.0,NaN,NaN,NaN,NaN,87.0,33.4,98.0,3.0,194.0,95.0,108.0,NaN,NaN,NaN,NaN,98.0,37.8,56.0,3.0,159.5,62.0,72.0,NaN,NaN,NaN,NaN,98.0,36.65,24.0,45.0,106.0,1.7,13.0,0.9,NaN,0.8,1.0,22.0,33.7,4.3,14.4,21.0,142.0,32.0,378.0,185.0,104.0,NaN,NaN,7.9,NaN,7.50,23.0,137.0,1106.0,2.0,24.0,2.8,NaN,2.1,1.00,23.0,29.5,4.4,3.9,1.3,147.0,37.0,117.0,41.0,105.0,NaN,NaN,6.1,NaN,7.38,99.0,2559.0,1.0,13.0
1,142676,12,1,31,468,0,57.0,0.0,NaN,NaN,0,0,0,NaN,15.0,229.0,86.0,NaN,51.0,77.33,130.0,22.0,NaN,35.3,NaN,15.0,198.0,92.0,NaN,77.0,100.70,148.0,14.0,NaN,37.6,NaN,14.0,79.0,72.0,NaN,37.0,63.0,110.0,11.0,NaN,35.3,NaN,15.0,273.0,109.0,NaN,79.0,100.70,148.0,30.0,NaN,37.9,NaN,15.0,192.5,89.0,NaN,53.0,81.670,130.0,17.0,NaN,36.70,NaN,NaN,NaN,NaN,35.0,NaN,NaN,0.7,NaN,7.0,43.8,3.1,NaN,2.0,148.0,NaN,NaN,616.0,NaN,NaN,NaN,22.4,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,0.4,NaN,21.0,32.5,3.2,NaN,1.8,134.0,NaN,NaN,517.0,NaN,NaN,NaN,15.1,NaN,NaN,NaN,NaN,NaN,NaN
2,142680,12,7,17,16,1,60.0,1.0,182.9,78.8,0,0,0,49.0,9.0,127.0,90.0,61.0,74.0,89.33,120.0,NaN,93.0,38.0,55.0,7.0,135.0,98.0,70.0,55.0,74.33,113.0,NaN,93.0,38.4,45.0,7.0,127.0,53.0,61.0,41.0,58.0,90.0,NaN,93.0,36.2,92.0,10.0,153.0,115.0,246.0,74.0,95.33,148.0,NaN,93.0,39.7,56.5,8.0,135.0,87.0,70.0,56.0,75.665,113.5,NaN,93.0,38.00,77.0,44.0,26.0,NaN,21.0,0.7,NaN,0.8,0.5,30.0,38.8,4.3,NaN,1.9,138.0,65.0,71.0,233.0,91.0,NaN,NaN,14.5,79.4,7.33,77.0,53.0,29.0,NaN,23.0,0.7,NaN,0.7,0.70,31.0,37.7,3.5,NaN,1.8,136.0,53.0,76.0,207.0,104.0,NaN,NaN,17.6,79.5,7.45,207.0,2570.0,1.0,20.0
3,142683,19,15,17,-1,0,64.0,1.0,180.3,145.2,0,1,0,76.0,3.0,191.0,87.0,75.0,NaN,NaN,NaN,NaN,95.0,37.4,59.0,3.0,166.0,68.0,84.0,NaN,NaN,NaN,NaN,97.0,37.0,40.0,3.0,166.0,62.0,29.0,NaN,NaN,NaN,NaN,89.0,36.6,90.0,3.0,191.0,87.0,113.0,NaN,NaN,NaN,NaN,97.0,38.0,58.0,3.0,178.5,74.0,77.0,NaN,NaN,NaN,NaN,92.5,37.20,39.0,160.0,186.0,1.6,11.0,0.7,NaN,0.9,1.0,18.0,33.9,4.9,1.8,1.6,138.0,45.0,294.0,104.0,137.0,NaN,NaN,18.3,NaN,7.33,49.0,1593.0,1933.0,3.0,19.0,1.8,NaN,1.4,0.65,24.0,28.3,5.0,4.5,2.4,137.0,42.0,107.0,79.0,140.0,NaN,NaN,18.3,NaN,7.36,374.0,2420.0,1.0,14.0
4,142688,3,0,9,-1,0,51.0,1.0,172.7,90.0,0,0,1,55.0,15.0,165.0,91.0,74.0,63.0,76.33,103.0,24.0,NaN,36.8,68.0,14.0,130.0,113.0,81.0,66.0,86.33,127.0,20.0,NaN,38.7,53.0,14.0,130.0,88.0,69.0,50.0,71.0,99.0,13.0,NaN,36.8,74.0,15.0,165.0,115.0,89.0,68.0,86.33,127.0,27.0,NaN,38.7,58.0,15.0,147.5,100.5,74.5,60.0,73.500,106.5,20.0,NaN,37.75,NaN,NaN,NaN,NaN,19.0,NaN,NaN,0.9,1.0,26.0,38.4,5.0,NaN,1.9,141.0,50.0,67.0,215.0,126.0,NaN,NaN,16.0,NaN,7.37,NaN,NaN,NaN,NaN,19.0,NaN,NaN,0.7,0.50,29.0,29.4,3.7,NaN,1.7,141.0,50.0,67.0,164.0,107.0,NaN,NaN,12.5,NaN,7.37,NaN,NaN,NaN,NaN

In [4]:
data.shape

(4000, 120)

In [5]:
len(data[data["In-hospital_death"]==1])

554

In [6]:
data[["SAPS-I", "SOFA", "Length_of_stay", "Survival", "Age"]]

      SAPS-I  SOFA  Length_of_stay  Survival   Age
0          6     1               5        -1  54.0
1         16     8               8        -1  76.0
2         21    11              19        -1  44.0
3          7     1               9       575  68.0
4         17     2               4       918  88.0
...      ...   ...             ...       ...   ...
3995      19     7              10       336  70.0
3996       8     2               3        -1  25.0
3997       8     5              11        -1  44.0
3998      22    10               8         7  37.0
3999      25    11               7        -1  78.0

[4000 rows x 5 columns]